Classification models 

Import the required library/packages 

In [36]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import matplotlib.pyplot as plt
import os

import re
import nltk
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [37]:
filename = '/content/News_Category2.csv' 
df = pd.read_csv(filename) #read the file 
df.head(1) #display the first row

category  ...                                          key_words
0    CRIME  ...  ['dewolf also told news 10 abc reporter lauren...

[1 rows x 7 columns]

In [38]:
df['label_id'] = pd.factorize(df.category)[0] #factorize category 
df[0:1] #looking at the first row

category  ... label_id
0    CRIME  ...        0

[1 rows x 8 columns]

In [39]:
label = df[['category','label_id']].copy() #return a new list but does not modify the orginal 
label[1500:2000]

category  label_id
1500    IMPACT         3
1501    IMPACT         3
1502    IMPACT         3
1503    IMPACT         3
1504    IMPACT         3
...        ...       ...
1995  POLITICS         4
1996  POLITICS         4
1997  POLITICS         4
1998  POLITICS         4
1999  POLITICS         4

[500 rows x 2 columns]

In [40]:
#convert to list
cat = list(label.category) 
id = list(label.label_id)

In [ ]:
len(cat),cat

In [ ]:
len(id),id

In [41]:
label_dict = {cat[i]: id[i] for i in range(len(cat))}  #Making dictionary of the categories and assigning their corresponding id

In [42]:
label_dict

{'ARTS': 30,
 'ARTS & CULTURE': 21,
 'BLACK VOICES': 6,
 'BUSINESS': 11,
 'COLLEGE': 19,
 'COMEDY': 8,
 'CRIME': 0,
 'CULTURE & ARTS': 40,
 'DIVORCE': 35,
 'EDUCATION': 18,
 'ENTERTAINMENT': 1,
 'ENVIRONMENT': 39,
 'FIFTY': 29,
 'FOOD & DRINK': 37,
 'GOOD NEWS': 27,
 'GREEN': 23,
 'HEALTHY LIVING': 25,
 'HOME & LIVING': 33,
 'IMPACT': 3,
 'LATINO VOICES': 17,
 'MEDIA': 13,
 'MONEY': 38,
 'PARENTING': 32,
 'PARENTS': 20,
 'POLITICS': 4,
 'QUEER VOICES': 9,
 'RELIGION': 15,
 'SCIENCE': 16,
 'SPORTS': 10,
 'STYLE': 22,
 'STYLE & BEAUTY': 34,
 'TASTE': 24,
 'TECH': 14,
 'THE WORLDPOST': 26,
 'TRAVEL': 12,
 'WEDDINGS': 36,
 'WEIRD NEWS': 5,
 'WELLNESS': 31,
 'WOMEN': 7,
 'WORLD NEWS': 2,
 'WORLDPOST': 28}

TFidfVectorizer is used to convert a collection of raw documnets into matrix of TF-IDF features.
TF is the number of times terms that appears in a documnet.
IDF is the inverse document frequency.

sublinear_tf is a boolean,defualt is False. Applies sublinear tf scalling, replaces tf with 1 + log(tf)

min_df is used to remove terms that appear infrequently.
if min_df was is set to 3 which means it ignores terms that appear less than 3 documents 

for encoding latin-1 is used 

for stop word enlgish is used 
ngram (1,4) is applied


In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(sublinear_tf=False, min_df=3, norm='l2', encoding='latin-1', ngram_range=(1,4),stop_words='english')
key_words_feat = vectorizer.fit_transform(df.key_words).toarray()
categories_label = df.label_id

In [ ]:
vectorizer.vocabulary_

In [45]:
key_words_feat.shape, categories_label.shape

((19298, 52345), (19298,))

Splitting data into train and test

25 percent of the data is used for testing purpose the rest for traning 
random state is set to 1000

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(key_words_feat,categories_label,test_size=0.25, random_state=1000)

In [47]:
X_train.shape,y_train.shape #looking at the shape rows and columns

((14473, 52345), (14473,))

Three different classifer are used:
1. LogisticRegression
2. MultinomialNB(used Bayseian model)
3. RandomForestClassifier

In [ ]:
from sklearn.linear_model import LogisticRegression #load the model 
clf1 = LogisticRegression(random_state=1000,max_iter=1000, multi_class='multinomial',solver='lbfgs',C=7) 
clf1.fit(X_train, y_train) #fitting the model
score = clf1.score(X_test, y_test) #obtain the score
print ("Accuracy of the model is : ",end="") 
print ("{0:.4f}".format(score)) 

Accuracy of the model is : 0.5442


In [ ]:
y_pred = clf1.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[90  0  0 ...  0  0  0]
 [ 1 76  3 ...  0  0  0]
 [ 3  0 52 ...  0  1  2]
 ...
 [ 0  0  0 ... 74  0  0]
 [ 3  2  0 ...  0 57  0]
 [ 0  4  0 ...  0  0 69]]
Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.71      0.65       127
           1       0.50      0.65      0.57       117
           2       0.41      0.45      0.43       115
           3       0.48      0.48      0.48       121
           4       0.49      0.51      0.50       123
           5       0.40      0.21      0.27        82
           6       0.60      0.52      0.56       101
           7       0.49      0.43      0.46       129
           8       0.49      0.62      0.55       113
           9       0.81      0.70      0.75        94
          10       0.70      0.80      0.75       108
          11       0.48      0.50      0.49       106
          12       0.56      0.51      0.53       137
          13       0.52      0.53      0.52   

In [ ]:
from sklearn.naive_bayes import MultinomialNB #load the model
clf2 = MultinomialNB() 
clf2.fit(X_train, y_train) #train the model 
score = clf2.score(X_test, y_test)
print ("Accuracy of the model is : ",end="") 
print ("{0:.4f}".format(score)) 

Accuracy of the model is : 0.5161


In [ ]:
y_pred = clf2.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[103   0   0 ...   0   0   0]
 [  2  70   3 ...   1   0   0]
 [  4   0  63 ...   0   0   1]
 ...
 [  0   0   0 ...  69   0   0]
 [  4   1   1 ...   1  53   0]
 [  0   3   0 ...   0   0  69]]
Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.81      0.61       127
           1       0.51      0.60      0.55       117
           2       0.36      0.55      0.44       115
           3       0.44      0.57      0.50       121
           4       0.42      0.60      0.50       123
           5       1.00      0.09      0.16        82
           6       0.71      0.36      0.47       101
           7       0.62      0.23      0.34       129
           8       0.54      0.56      0.55       113
           9       0.72      0.68      0.70        94
          10       0.65      0.82      0.73       108
          11       0.50      0.47      0.48       106
          12       0.65      0.50      0.56       137
          

In [ ]:
from sklearn.ensemble import RandomForestClassifier #load the model 
clf3 = RandomForestClassifier()
clf3.fit(X_train, y_train) #fit the model 
score = clf3.score(X_test, y_test)
print ("Accuracy of the model is : ",end="") 
print ("{0:.4f}".format(score)) 

Accuracy of the model is : 0.4528


In [ ]:
y_pred = clf3.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[92  0  1 ...  0  0  1]
 [ 3 61  4 ...  0  0  3]
 [ 7  2 36 ...  0  0  2]
 ...
 [ 0  0  0 ... 64  0  0]
 [10  3  2 ...  0 46  0]
 [ 0  7  0 ...  0  1 72]]
Classification Report:
              precision    recall  f1-score   support

           0       0.39      0.72      0.51       127
           1       0.31      0.52      0.39       117
           2       0.37      0.31      0.34       115
           3       0.39      0.22      0.28       121
           4       0.42      0.49      0.45       123
           5       0.34      0.17      0.23        82
           6       0.44      0.35      0.39       101
           7       0.41      0.37      0.39       129
           8       0.32      0.59      0.42       113
           9       0.74      0.68      0.71        94
          10       0.47      0.79      0.59       108
          11       0.44      0.42      0.43       106
          12       0.54      0.47      0.50       137
          13       0.44      0.35      0.39   